version: '2'
services:
    web:
        build: ./
        command: python ./src/manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - ./:/data
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://postgres@db/postgres
    db:
        image: postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
