version: '2'
services:
    web:
        build: ./
        ports:
            - 8000:8000
        volumes:
            - ./:/data
        depends_on:
            - db
        environment:
            DATABASE_URL: postgres://postgres@db/postgres
            PORT: 8000
    db:
        image: postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
